"""Central authorization policy for state-changing HTTP routes.

Every POST/PUT/PATCH/DELETE route must be listed here or it is denied by the
global middleware. This is deliberately explicit so adding an endpoint cannot
silently make a new clinical write available to every JWT holder.
"""

MUTATING_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})

PUBLIC_ROUTE_TEMPLATES = frozenset({
    ("GET", "/docs"),
    ("GET", "/docs/oauth2-redirect"),
    ("GET", "/redoc"),
    ("GET", "/openapi.json"),
    ("GET", "/health"),
    ("GET", "/readiness"),
    ("POST", "/api/auth/login/admin"),
    ("POST", "/api/auth/login/biometric"),
    ("POST", "/api/biometrics/challenge"),
    ("GET", "/verificar"),
    ("GET", "/verificar/documento"),
    ("GET", "/verificar/expediente"),
    ("GET", "/verificar/expediente/{pt_num}"),
    ("GET", "/api/verificar"),
    ("GET", "/api/verificar/documento"),
    ("GET", "/api/verificar/expediente"),
    ("GET", "/api/verificar/expediente/{pt_num}"),
    ("GET", "/api/verificar/documento-estado"),
    ("GET", "/api/verificar/pdf/documento"),
    ("GET", "/verificar/pdf/documento"),
    ("GET", "/api/verificar/pdf"),
    ("GET", "/verificar/pdf"),
    ("GET", "/api/verificar/pdf/{pt_num}"),
    ("GET", "/verificar/pdf/{pt_num}"),
    ("GET", "/static/logo.png"),
    ("GET", "/static/hospital-logo.png"),
    ("GET", "/assets"),
})

PUBLIC_SPA_PATHS = frozenset({
    "/",
    "/login",
    "/sin-acceso",
    "/admin",
    "/rh",
    "/camas",
    "/captura",
    "/firma-express",
    "/firmas-area",
    "/ehr",
    "/agenda",
    "/logo.png",
    "/websdk.client.min.js",
})

# Rutas de React Router que necesitan entregar index.html en producción. La
# pantalla es pública; la consulta clínica que hace React sigue protegida por
# JWT en /api/ehr/paciente/{pt_num}.
PUBLIC_SPA_DYNAMIC_PREFIXES = frozenset({"/ehr/"})

ADMIN_SYSTEMS = frozenset({"admin", "sistemas"})
ADMIN_RH_SYSTEMS = frozenset({"admin", "rh", "sistemas"})
ADMIN_RH = frozenset({"admin", "rh"})
PATIENT_OPERATIONS = frozenset({"admin", "sistemas", "enfermeria"})
CLINICAL_STAFF = frozenset({"admin", "sistemas", "medico", "ayudante", "enfermeria"})
from access_control import LOCAL_ROLES
SPECIAL_SIGNATURE_STAFF = CLINICAL_STAFF | LOCAL_ROLES  # Endpoint checks exact area/format/self identity.
MEDICAL_STAFF = frozenset({"admin", "medico", "ayudante"})
CLINICAL_READ_STAFF = frozenset({"medico", "ayudante", "enfermeria"})

CLINICAL_PDF_ROUTE_TEMPLATES = frozenset({
    "/api/atenciones/{folio}/pdf",
    "/api/kh/estudios/{ptmt_num}/pdf",
    "/kh/estudios/{ptmt_num}/pdf",
    "/api/api/kh/estudios/{ptmt_num}/pdf",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-32-01",
    "/api/ehr/paciente/{pt_num}/pdf-nota-urgencias",
    "/api/ehr/paciente/{pt_num}/pdf-expediente-completo",
    "/ehr/paciente/{pt_num}/pdf-expediente-completo",
    "/api/ehr/paciente/{pt_num}/pdf-nota-hospitalizacion",
    "/api/verificar/pdf/documento",
    "/verificar/pdf/documento",
    "/api/verificar/pdf",
    "/verificar/pdf",
    "/api/verificar/pdf/{pt_num}",
    "/verificar/pdf/{pt_num}",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-eed",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-25",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-34-01",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-12",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-04",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-04",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-15",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-15",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-02",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-02",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-07",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-07",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-08",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-08",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-43",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-43",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-11",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-11",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-19",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-19",
    "/api/ehr/paciente/{pt_num}/pdf-egreso-voluntario-15",
    "/ehr/paciente/{pt_num}/pdf-egreso-voluntario-15",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-06",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-06",
    "/api/ehr/paciente/{pt_num}/pdf-consentimiento-09",
    "/ehr/paciente/{pt_num}/pdf-consentimiento-09",
    "/api/ehr/paciente/{pt_num}/pdf-egreso-resumen-16",
    "/ehr/paciente/{pt_num}/pdf-egreso-resumen-16",
})

CLINICAL_READ_ROUTE_TEMPLATES = CLINICAL_PDF_ROUTE_TEMPLATES | frozenset({
    "/api/pacientes",
    "/api/pacientes/altas",
    "/api/pacientes/{paciente_id}/firmantes-biometricos",
    "/api/ehr/paciente/{paciente_id}/firmantes-biometricos",
    "/api/pacientes/{paciente_id}/traslados",
    "/api/pacientes/{paciente_id}/journey",
    "/api/atenciones/pendientes/{medico_id}",
    "/api/atenciones/historial/{medico_id}",
    "/api/atenciones/mis-registros",
    "/api/atenciones/global",
    "/api/atenciones/todas",
    "/api/atenciones/exportar",
    "/api/camas",
    "/api/camas/paciente/{pt_num}",
    "/api/camas/ocupacion",
    "/api/ehr/paciente/{pt_num}",
    "/api/ehr/paciente/{pt_num}/evoluciones-hospitalizacion",
    "/api/ehr/paciente/{pt_num}/signos-vitales",
    "/api/ehr/paciente/{pt_num}/historial-signos-vitales",
    "/api/ehr/paciente/{pt_num}/medicamentos",
    "/api/ehr/paciente/{pt_num}/dieta-cuidados",
    "/api/ehr/pacientes/buscar",
    "/api/ehr/alergias/catalogo",
    "/api/ehr/paciente/{pt_num}/alergias",
    "/api/ehr/paciente/{pt_num}/firmas",
    "/api/pacientes/{pt_num}/firmas",
    "/api/ehr/paciente/{pt_num}/firmas-documento",
    "/ehr/paciente/{pt_num}/firmas-documento",
    "/api/ehr/banco-sangre/firmantes",
    "/api/ehr/firmantes-especiales",
    "/api/ehr/paciente/{pt_num}/historial-auditoria",
    "/api/ehr/paciente/{pt_num}/verificar-documento-estado",
    "/api/ehr/paciente/{pt_num}/consentimiento-25",
    "/api/ehr/paciente/{pt_num}/consentimiento-34-01",
    "/api/ehr/paciente/{pt_num}/consentimiento-12",
    "/api/ehr/paciente/{pt_num}/consentimiento-04",
    "/api/ehr/paciente/{pt_num}/consentimiento-15",
    "/api/ehr/paciente/{pt_num}/consentimiento-02",
    "/api/ehr/paciente/{pt_num}/consentimiento-07",
    "/ehr/paciente/{pt_num}/consentimiento-07",
    "/api/ehr/paciente/{pt_num}/consentimiento-08",
    "/ehr/paciente/{pt_num}/consentimiento-08",
    "/api/ehr/paciente/{pt_num}/consentimiento-43",
    "/api/ehr/paciente/{pt_num}/consentimiento-11",
    "/ehr/paciente/{pt_num}/consentimiento-11",
    "/api/ehr/paciente/{pt_num}/consentimiento-19",
    "/ehr/paciente/{pt_num}/consentimiento-19",
    "/api/ehr/paciente/{pt_num}/egreso-voluntario-15",
    "/ehr/paciente/{pt_num}/egreso-voluntario-15",
    "/api/ehr/paciente/{pt_num}/consentimiento-15-ev",
    "/ehr/paciente/{pt_num}/consentimiento-15-ev",
    "/api/ehr/paciente/{pt_num}/consentimiento-06",
    "/ehr/paciente/{pt_num}/consentimiento-06",
    "/api/ehr/paciente/{pt_num}/consentimiento-09",
    "/ehr/paciente/{pt_num}/consentimiento-09",
    "/api/ehr/paciente/{pt_num}/egreso-resumen-16",
    "/ehr/paciente/{pt_num}/egreso-resumen-16",
    "/api/ehr/paciente/{pt_num}/formato-historial",
})

READ_ROLE_POLICIES = {
    ("GET", path): CLINICAL_READ_STAFF for path in CLINICAL_READ_ROUTE_TEMPLATES
}


WRITE_ROLE_POLICIES = {
    # Identity and administration (roles already established in endpoint code).
    ("POST", "/api/auth/impersonate"): ADMIN_SYSTEMS,
    ("POST", "/api/auth/logout"): frozenset({"admin", "sistemas", "rh", "enfermeria", "trabajo_social", "limpieza", "medico", "ayudante"}),
    ("POST", "/api/auth/change-password"): frozenset({"admin", "sistemas", "rh", "enfermeria", "trabajo_social", "limpieza"}),
    ("POST", "/api/medicos"): ADMIN_RH_SYSTEMS,
    ("POST", "/api/usuarios"): ADMIN_RH_SYSTEMS,
    ("PUT", "/api/usuarios/{usuario_id}"): ADMIN_SYSTEMS,
    ("PUT", "/api/usuarios/{usuario_id}/password"): ADMIN_SYSTEMS,
    ("DELETE", "/api/usuarios/{usuario_id}"): frozenset({"sistemas"}),
    ("POST", "/api/usuarios/{usuario_id}/biometria/enrolar"): ADMIN_SYSTEMS,
    ("POST", "/api/usuarios/{usuario_id}/biometria/reenrolar"): ADMIN_SYSTEMS,
    ("PUT", "/api/medicos/{medico_id}"): ADMIN_RH_SYSTEMS,
    ("PUT", "/api/medicos/{medico_id}/permisos"): ADMIN_SYSTEMS,
    ("PUT", "/api/medicos/{medico_id}/datos"): ADMIN_RH_SYSTEMS,
    ("PUT", "/api/medicos/{medico_id}/huella"): ADMIN_RH_SYSTEMS,
    ("POST", "/api/medicos/{medico_id}/biometria/enrolar"): ADMIN_RH_SYSTEMS,
    ("POST", "/api/medicos/{medico_id}/biometria/reenrolar"): ADMIN_RH_SYSTEMS,
    ("POST", "/api/medicos/{medico_id}/fea/completar-actualizacion"): ADMIN_RH_SYSTEMS,
    ("POST", "/api/firmas/{firma_id}/tsa/reintentar"): MEDICAL_STAFF,
    ("POST", "/api/clinical-sync/reconcile"): ADMIN_SYSTEMS,
    ("POST", "/api/catalogos/areas"): ADMIN_RH_SYSTEMS,
    ("DELETE", "/api/catalogos/areas/{id}"): ADMIN_SYSTEMS,
    ("POST", "/api/catalogos/tipos"): ADMIN_RH_SYSTEMS,
    ("DELETE", "/api/catalogos/tipos/{id}"): ADMIN_SYSTEMS,
    ("POST", "/api/catalogos/formatos"): ADMIN_SYSTEMS,
    ("POST", "/api/escaneos"): ADMIN_RH,
    ("PUT", "/api/escaneos/{escaneo_id}"): ADMIN_RH,
    ("DELETE", "/api/escaneos/{escaneo_id}"): ADMIN_RH,
    ("PUT", "/api/camas/{numero_cama}/limpieza"): frozenset(
        {"admin", "sistemas", "limpieza"}
    ),

    # Patient/episode operations inferred from the current frontend role gates.
    ("POST", "/api/pacientes"): PATIENT_OPERATIONS,
    ("POST", "/api/pacientes/sincronizar-kh"): PATIENT_OPERATIONS,
    ("PUT", "/api/pacientes/{paciente_id}"): PATIENT_OPERATIONS,
    ("PUT", "/api/pacientes/{paciente_id}/alta"): PATIENT_OPERATIONS,
    ("PUT", "/api/ehr/paciente/{paciente_id}/alta"): PATIENT_OPERATIONS,
    ("PUT", "/api/pacientes/{paciente_id}/reingresar"): PATIENT_OPERATIONS,
    ("PUT", "/api/ehr/paciente/{paciente_id}/reingresar"): PATIENT_OPERATIONS,
    ("POST", "/api/pacientes/{paciente_id}/firmantes-biometricos"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{paciente_id}/firmantes-biometricos"): CLINICAL_STAFF,
    ("POST", "/api/pacientes/{paciente_id}/firmantes-biometricos/{firmante_id}/enrolar"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{paciente_id}/firmantes-biometricos/{firmante_id}/enrolar"): CLINICAL_STAFF,
    ("POST", "/api/pacientes/{paciente_id}/firmantes-biometricos/{firmante_id}/reenrolar"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{paciente_id}/firmantes-biometricos/{firmante_id}/reenrolar"): CLINICAL_STAFF,
    ("PUT", "/api/pacientes/{paciente_id}/firmantes-biometricos/{firmante_id}"): CLINICAL_STAFF,
    ("PUT", "/api/ehr/paciente/{paciente_id}/firmantes-biometricos/{firmante_id}"): CLINICAL_STAFF,
    ("POST", "/api/pacientes/{paciente_id}/firmantes-biometricos/verificar"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{paciente_id}/firmantes-biometricos/verificar"): CLINICAL_STAFF,
    ("DELETE", "/api/pacientes/{paciente_id}/firmantes-biometricos/{firmante_id}"): CLINICAL_STAFF,
    ("DELETE", "/api/ehr/paciente/{paciente_id}/firmantes-biometricos/{firmante_id}"): CLINICAL_STAFF,
    ("POST", "/api/atenciones/pre-captura"): PATIENT_OPERATIONS,
    ("POST", "/api/atenciones/firmar-lote"): MEDICAL_STAFF,
    ("POST", "/api/atenciones/{folio}/notas"): CLINICAL_STAFF,
    ("PUT", "/api/atenciones/{folio}/reaperturar"): frozenset({"sistemas"}),
    ("PUT", "/api/atenciones/{folio}/autorizar"): frozenset({"sistemas"}),
    ("POST", "/api/agenda/citas"): CLINICAL_STAFF,

    # Clinical EHR writes. The broad set mirrors the current PatientDashboard
    # route gate; operation-specific RBAC remains a documented follow-up.
    ("POST", "/api/ehr/paciente/{pt_num}/nota-hospitalizacion"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-32-01"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/nota-urgencias"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/signos-vitales"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/medicamentos/prescribir-biometrico"): MEDICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/medicamentos/discontinuar-biometrico"): MEDICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/dieta-cuidados/prescribir-biometrico"): MEDICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/alergias/registrar"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/alergias/inactivar"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/alergias/actualizar-texto"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/firmar-biometrico"): MEDICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/firmar-biometrico-firmante"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/firmar-biometrico-banco-sangre"): SPECIAL_SIGNATURE_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/firmar-biometrico-especial"): SPECIAL_SIGNATURE_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/firmar-biometrico-firmante"): CLINICAL_STAFF,
    ("POST", "/api/pacientes/{pt_num}/firmar-biometrico-firmante"): CLINICAL_STAFF,
    ("POST", "/pacientes/{pt_num}/firmar-biometrico-firmante"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/verificar-integridad"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/verificar-integridad"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-eed"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-25"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-34-01"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-12"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-04"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-15"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-02"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/pdf-preparar"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-07"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/consentimiento-07"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-08"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-43"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-11"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/consentimiento-11"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-19"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/consentimiento-19"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/egreso-voluntario-15"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/egreso-voluntario-15"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-15-ev"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/consentimiento-15-ev"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-06"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/consentimiento-06"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/consentimiento-09"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/consentimiento-09"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/egreso-resumen-16"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/egreso-resumen-16"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/formato-crear-registro"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/formato-crear-registro"): CLINICAL_STAFF,
    ("POST", "/api/ehr/paciente/{pt_num}/formato-guardar-registro"): CLINICAL_STAFF,
    ("POST", "/ehr/paciente/{pt_num}/formato-guardar-registro"): CLINICAL_STAFF,
}


# These writes cannot be assigned safely from current code/docs. They are not
# present in WRITE_ROLE_POLICIES, so the middleware rejects them for every role.
REQUIRES_FUNCTIONAL_DECISION = frozenset({
    ("PUT", "/api/atenciones/{folio}"),
})
