"""initial PostgreSQL schema

Revision ID: 9024a9c93603
Revises: 
Create Date: 2026-09-17 13:37:32.962515
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9024a9c93603'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_cama', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('estado_limpieza', sa.String(), nullable=True),
    sa.Column('notas_limpieza', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camas_area'), 'camas', ['area'], unique=False)
    op.create_index(op.f('ix_camas_id'), 'camas', ['id'], unique=False)
    op.create_index(op.f('ix_camas_numero_cama'), 'camas', ['numero_cama'], unique=True)
    op.create_table('catalogo_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_areas_id'), 'catalogo_areas', ['id'], unique=False)
    op.create_index(op.f('ix_catalogo_areas_nombre'), 'catalogo_areas', ['nombre'], unique=True)
    op.create_table('catalogo_formatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_formatos_codigo'), 'catalogo_formatos', ['codigo'], unique=False)
    op.create_index(op.f('ix_catalogo_formatos_id'), 'catalogo_formatos', ['id'], unique=False)
    op.create_table('catalogo_tipos_atencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_tipos_atencion_id'), 'catalogo_tipos_atencion', ['id'], unique=False)
    op.create_index(op.f('ix_catalogo_tipos_atencion_nombre'), 'catalogo_tipos_atencion', ['nombre'], unique=True)
    op.create_table('documentos_verificacion_qr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_uuid', sa.String(length=128), nullable=False),
    sa.Column('pt_num', sa.String(length=50), nullable=False),
    sa.Column('expediente', sa.String(length=50), nullable=True),
    sa.Column('codigo_formato', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=255), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=False),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('medico_nombre', sa.String(length=255), nullable=True),
    sa.Column('medico_cedula', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_qr_pt_formato_slot', 'documentos_verificacion_qr', ['pt_num', 'codigo_formato', 'slot'], unique=False)
    op.create_index(op.f('ix_documentos_verificacion_qr_codigo_formato'), 'documentos_verificacion_qr', ['codigo_formato'], unique=False)
    op.create_index(op.f('ix_documentos_verificacion_qr_doc_uuid'), 'documentos_verificacion_qr', ['doc_uuid'], unique=True)
    op.create_index(op.f('ix_documentos_verificacion_qr_fecha_generacion'), 'documentos_verificacion_qr', ['fecha_generacion'], unique=False)
    op.create_index(op.f('ix_documentos_verificacion_qr_id'), 'documentos_verificacion_qr', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_verificacion_qr_pt_num'), 'documentos_verificacion_qr', ['pt_num'], unique=False)
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_empleado', sa.String(), nullable=True),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('especialidad', sa.String(), nullable=True),
    sa.Column('cedula', sa.String(), nullable=True),
    sa.Column('huella_token', sa.String(), nullable=True),
    sa.Column('fmd_template', sa.String(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('activo_status', sa.Boolean(), nullable=True),
    sa.Column('bajo_contrato', sa.Boolean(), nullable=True),
    sa.Column('horario_laboral', sa.String(), nullable=True),
    sa.Column('es_ayudante', sa.Boolean(), nullable=True),
    sa.Column('medico_asignado_id', sa.Integer(), nullable=True),
    sa.Column('public_key_pem', sa.Text(), nullable=True),
    sa.Column('private_key_enc', sa.Text(), nullable=True),
    sa.Column('formatos_permitidos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medico_asignado_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicos_huella_token'), 'medicos', ['huella_token'], unique=True)
    op.create_index(op.f('ix_medicos_id'), 'medicos', ['id'], unique=False)
    op.create_index(op.f('ix_medicos_nombre_completo'), 'medicos', ['nombre_completo'], unique=False)
    op.create_index(op.f('ix_medicos_numero_empleado'), 'medicos', ['numero_empleado'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('permisos_modulos', sa.Text(), nullable=True),
    sa.Column('formatos_permitidos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('auditoria_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('detalles_json', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_logs_id'), 'auditoria_logs', ['id'], unique=False)
    op.create_table('dieta_cuidados_prescripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pt_num', sa.String(length=50), nullable=False),
    sa.Column('expediente', sa.String(length=50), nullable=True),
    sa.Column('tipo_dieta', sa.String(length=100), nullable=False),
    sa.Column('horario', sa.String(length=50), nullable=True),
    sa.Column('fase_clinica', sa.String(length=255), nullable=True),
    sa.Column('indicaciones_nutricionales', sa.Text(), nullable=True),
    sa.Column('inicio_ayuno_dieta', sa.String(length=100), nullable=True),
    sa.Column('nutriologo_responsable', sa.String(length=255), nullable=True),
    sa.Column('alergias_alimentarias', sa.String(length=255), nullable=True),
    sa.Column('tolerancia_via_oral', sa.String(length=255), nullable=True),
    sa.Column('cuidados_enfermeria_json', sa.Text(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('medico_nombre', sa.String(length=255), nullable=True),
    sa.Column('medico_cedula', sa.String(length=100), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('sello_digital', sa.Text(), nullable=True),
    sa.Column('cadena_original', sa.Text(), nullable=True),
    sa.Column('fecha_hora_prescripcion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dieta_cuidados_prescripciones_fecha_hora_prescripcion'), 'dieta_cuidados_prescripciones', ['fecha_hora_prescripcion'], unique=False)
    op.create_index(op.f('ix_dieta_cuidados_prescripciones_id'), 'dieta_cuidados_prescripciones', ['id'], unique=False)
    op.create_index(op.f('ix_dieta_cuidados_prescripciones_pt_num'), 'dieta_cuidados_prescripciones', ['pt_num'], unique=False)
    op.create_table('escaneos_rh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('nombre_archivo', sa.String(), nullable=True),
    sa.Column('ruta_archivo', sa.String(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escaneos_rh_id'), 'escaneos_rh', ['id'], unique=False)
    op.create_index(op.f('ix_escaneos_rh_titulo'), 'escaneos_rh', ['titulo'], unique=False)
    op.create_table('historial_llaves_fea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_inactivacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_llaves_fea_id'), 'historial_llaves_fea', ['id'], unique=False)
    op.create_index(op.f('ix_historial_llaves_fea_medico_id'), 'historial_llaves_fea', ['medico_id'], unique=False)
    op.create_table('historico_notas_clinicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_formato', sa.String(), nullable=True),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('pt_num', sa.String(), nullable=True),
    sa.Column('expediente', sa.String(), nullable=True),
    sa.Column('evolution_slot', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('nombre_medico', sa.String(), nullable=True),
    sa.Column('cedula_profesional', sa.String(), nullable=True),
    sa.Column('contenido_soap_json', sa.Text(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historico_pt_formato_fecha', 'historico_notas_clinicas', ['pt_num', 'codigo_formato', 'fecha_registro'], unique=False)
    op.create_index(op.f('ix_historico_notas_clinicas_codigo_formato'), 'historico_notas_clinicas', ['codigo_formato'], unique=False)
    op.create_index(op.f('ix_historico_notas_clinicas_expediente'), 'historico_notas_clinicas', ['expediente'], unique=False)
    op.create_index(op.f('ix_historico_notas_clinicas_fecha_registro'), 'historico_notas_clinicas', ['fecha_registro'], unique=False)
    op.create_index(op.f('ix_historico_notas_clinicas_id'), 'historico_notas_clinicas', ['id'], unique=False)
    op.create_index(op.f('ix_historico_notas_clinicas_pt_num'), 'historico_notas_clinicas', ['pt_num'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('num_habitacion', sa.String(), nullable=True),
    sa.Column('area_hospitalaria', sa.String(), nullable=True),
    sa.Column('codigo_barras', sa.String(), nullable=True),
    sa.Column('status_ingreso', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('dado_de_alta_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.Column('registrado_por_nombre', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['dado_de_alta_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_codigo_barras'), 'pacientes', ['codigo_barras'], unique=False)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_index(op.f('ix_pacientes_nombre_completo'), 'pacientes', ['nombre_completo'], unique=False)
    op.create_index(op.f('ix_pacientes_num_habitacion'), 'pacientes', ['num_habitacion'], unique=False)
    op.create_table('procedimientos_frecuentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('nombre_procedimiento', sa.String(), nullable=True),
    sa.Column('frecuencia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedimientos_frecuentes_id'), 'procedimientos_frecuentes', ['id'], unique=False)
    op.create_index(op.f('ix_procedimientos_frecuentes_medico_id'), 'procedimientos_frecuentes', ['medico_id'], unique=False)
    op.create_table('atenciones_medicas',
    sa.Column('folio', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_realizacion', sa.DateTime(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('area_hospitalaria', sa.String(), nullable=True),
    sa.Column('tipo_atencion', sa.String(), nullable=True),
    sa.Column('nombre_procedimiento', sa.String(), nullable=True),
    sa.Column('habitacion_capturada', sa.String(), nullable=True),
    sa.Column('procedimiento_detalle', sa.Text(), nullable=True),
    sa.Column('fecha_firma', sa.DateTime(), nullable=True),
    sa.Column('hash_seguridad', sa.String(), nullable=True),
    sa.Column('ruta_archivo_firmado', sa.String(), nullable=True),
    sa.Column('estatus_pago', sa.String(), nullable=True),
    sa.Column('reaperturado', sa.Boolean(), nullable=True),
    sa.Column('registrado_por_nombre', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('folio')
    )
    op.create_index('idx_atenciones_med_fecha_pago', 'atenciones_medicas', ['medico_id', 'fecha_realizacion', 'estatus_pago'], unique=False)
    op.create_index(op.f('ix_atenciones_medicas_folio'), 'atenciones_medicas', ['folio'], unique=False)
    op.create_table('biometria_firmantes_episodio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('pt_num', sa.String(length=50), nullable=True),
    sa.Column('tipo_firmante', sa.String(length=50), nullable=True),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('parentesco', sa.String(length=100), nullable=True),
    sa.Column('identificacion_oficial', sa.String(length=100), nullable=True),
    sa.Column('domicilio', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fmd_template', sa.Text(), nullable=True),
    sa.Column('huella_token', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_inactivacion', sa.DateTime(), nullable=True),
    sa.Column('inactivado_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inactivado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biometria_firmantes_episodio_estado'), 'biometria_firmantes_episodio', ['estado'], unique=False)
    op.create_index(op.f('ix_biometria_firmantes_episodio_fecha_registro'), 'biometria_firmantes_episodio', ['fecha_registro'], unique=False)
    op.create_index(op.f('ix_biometria_firmantes_episodio_huella_token'), 'biometria_firmantes_episodio', ['huella_token'], unique=True)
    op.create_index(op.f('ix_biometria_firmantes_episodio_id'), 'biometria_firmantes_episodio', ['id'], unique=False)
    op.create_index(op.f('ix_biometria_firmantes_episodio_nombre_completo'), 'biometria_firmantes_episodio', ['nombre_completo'], unique=False)
    op.create_index(op.f('ix_biometria_firmantes_episodio_paciente_id'), 'biometria_firmantes_episodio', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_biometria_firmantes_episodio_pt_num'), 'biometria_firmantes_episodio', ['pt_num'], unique=False)
    op.create_index(op.f('ix_biometria_firmantes_episodio_tipo_firmante'), 'biometria_firmantes_episodio', ['tipo_firmante'], unique=False)
    op.create_table('citas_medicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('nombre_paciente_manual', sa.String(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('lugar', sa.String(), nullable=True),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_medicas_fecha_hora'), 'citas_medicas', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_citas_medicas_id'), 'citas_medicas', ['id'], unique=False)
    op.create_index(op.f('ix_citas_medicas_medico_id'), 'citas_medicas', ['medico_id'], unique=False)
    op.create_index(op.f('ix_citas_medicas_paciente_id'), 'citas_medicas', ['paciente_id'], unique=False)
    op.create_table('traslados_pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('origen_area', sa.String(), nullable=True),
    sa.Column('origen_habitacion', sa.String(), nullable=True),
    sa.Column('destino_area', sa.String(), nullable=True),
    sa.Column('destino_habitacion', sa.String(), nullable=True),
    sa.Column('fecha_traslado', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traslados_pacientes_id'), 'traslados_pacientes', ['id'], unique=False)
    op.create_table('firmas_documentos_clinicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('codigo_formato', sa.String(), nullable=True),
    sa.Column('pt_num', sa.String(), nullable=True),
    sa.Column('expediente', sa.String(), nullable=True),
    sa.Column('evolution_slot', sa.Integer(), nullable=True),
    sa.Column('rol_firmante', sa.String(), nullable=True),
    sa.Column('firmante_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('nombre_medico', sa.String(), nullable=True),
    sa.Column('cedula_profesional', sa.String(), nullable=True),
    sa.Column('fecha_hora_firma', sa.DateTime(), nullable=True),
    sa.Column('metodo_autenticacion', sa.String(), nullable=True),
    sa.Column('hash_sha256', sa.String(), nullable=True),
    sa.Column('sello_digital', sa.Text(), nullable=True),
    sa.Column('cadena_original', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('tsa_token', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_revocacion', sa.DateTime(), nullable=True),
    sa.Column('motivo_revocacion', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firmante_id'], ['biometria_firmantes_episodio.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_firmas_pt_formato_slot_estado', 'firmas_documentos_clinicos', ['pt_num', 'codigo_formato', 'evolution_slot', 'estado'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_codigo_formato'), 'firmas_documentos_clinicos', ['codigo_formato'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_estado'), 'firmas_documentos_clinicos', ['estado'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_expediente'), 'firmas_documentos_clinicos', ['expediente'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_fecha_hora_firma'), 'firmas_documentos_clinicos', ['fecha_hora_firma'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_id'), 'firmas_documentos_clinicos', ['id'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_medico_id'), 'firmas_documentos_clinicos', ['medico_id'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_pt_num'), 'firmas_documentos_clinicos', ['pt_num'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_rol_firmante'), 'firmas_documentos_clinicos', ['rol_firmante'], unique=False)
    op.create_index(op.f('ix_firmas_documentos_clinicos_tipo_documento'), 'firmas_documentos_clinicos', ['tipo_documento'], unique=False)
    op.create_table('notas_enfermeria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atencion_folio', sa.String(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('creada_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atencion_folio'], ['atenciones_medicas.folio'], ),
    sa.ForeignKeyConstraint(['creada_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_enfermeria_id'), 'notas_enfermeria', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_enfermeria_id'), table_name='notas_enfermeria')
    op.drop_table('notas_enfermeria')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_tipo_documento'), table_name='firmas_documentos_clinicos')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_rol_firmante'), table_name='firmas_documentos_clinicos')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_pt_num'), table_name='firmas_documentos_clinicos')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_medico_id'), table_name='firmas_documentos_clinicos')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_id'), table_name='firmas_documentos_clinicos')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_fecha_hora_firma'), table_name='firmas_documentos_clinicos')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_expediente'), table_name='firmas_documentos_clinicos')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_estado'), table_name='firmas_documentos_clinicos')
    op.drop_index(op.f('ix_firmas_documentos_clinicos_codigo_formato'), table_name='firmas_documentos_clinicos')
    op.drop_index('idx_firmas_pt_formato_slot_estado', table_name='firmas_documentos_clinicos')
    op.drop_table('firmas_documentos_clinicos')
    op.drop_index(op.f('ix_traslados_pacientes_id'), table_name='traslados_pacientes')
    op.drop_table('traslados_pacientes')
    op.drop_index(op.f('ix_citas_medicas_paciente_id'), table_name='citas_medicas')
    op.drop_index(op.f('ix_citas_medicas_medico_id'), table_name='citas_medicas')
    op.drop_index(op.f('ix_citas_medicas_id'), table_name='citas_medicas')
    op.drop_index(op.f('ix_citas_medicas_fecha_hora'), table_name='citas_medicas')
    op.drop_table('citas_medicas')
    op.drop_index(op.f('ix_biometria_firmantes_episodio_tipo_firmante'), table_name='biometria_firmantes_episodio')
    op.drop_index(op.f('ix_biometria_firmantes_episodio_pt_num'), table_name='biometria_firmantes_episodio')
    op.drop_index(op.f('ix_biometria_firmantes_episodio_paciente_id'), table_name='biometria_firmantes_episodio')
    op.drop_index(op.f('ix_biometria_firmantes_episodio_nombre_completo'), table_name='biometria_firmantes_episodio')
    op.drop_index(op.f('ix_biometria_firmantes_episodio_id'), table_name='biometria_firmantes_episodio')
    op.drop_index(op.f('ix_biometria_firmantes_episodio_huella_token'), table_name='biometria_firmantes_episodio')
    op.drop_index(op.f('ix_biometria_firmantes_episodio_fecha_registro'), table_name='biometria_firmantes_episodio')
    op.drop_index(op.f('ix_biometria_firmantes_episodio_estado'), table_name='biometria_firmantes_episodio')
    op.drop_table('biometria_firmantes_episodio')
    op.drop_index(op.f('ix_atenciones_medicas_folio'), table_name='atenciones_medicas')
    op.drop_index('idx_atenciones_med_fecha_pago', table_name='atenciones_medicas')
    op.drop_table('atenciones_medicas')
    op.drop_index(op.f('ix_procedimientos_frecuentes_medico_id'), table_name='procedimientos_frecuentes')
    op.drop_index(op.f('ix_procedimientos_frecuentes_id'), table_name='procedimientos_frecuentes')
    op.drop_table('procedimientos_frecuentes')
    op.drop_index(op.f('ix_pacientes_num_habitacion'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_nombre_completo'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_codigo_barras'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_historico_notas_clinicas_pt_num'), table_name='historico_notas_clinicas')
    op.drop_index(op.f('ix_historico_notas_clinicas_id'), table_name='historico_notas_clinicas')
    op.drop_index(op.f('ix_historico_notas_clinicas_fecha_registro'), table_name='historico_notas_clinicas')
    op.drop_index(op.f('ix_historico_notas_clinicas_expediente'), table_name='historico_notas_clinicas')
    op.drop_index(op.f('ix_historico_notas_clinicas_codigo_formato'), table_name='historico_notas_clinicas')
    op.drop_index('idx_historico_pt_formato_fecha', table_name='historico_notas_clinicas')
    op.drop_table('historico_notas_clinicas')
    op.drop_index(op.f('ix_historial_llaves_fea_medico_id'), table_name='historial_llaves_fea')
    op.drop_index(op.f('ix_historial_llaves_fea_id'), table_name='historial_llaves_fea')
    op.drop_table('historial_llaves_fea')
    op.drop_index(op.f('ix_escaneos_rh_titulo'), table_name='escaneos_rh')
    op.drop_index(op.f('ix_escaneos_rh_id'), table_name='escaneos_rh')
    op.drop_table('escaneos_rh')
    op.drop_index(op.f('ix_dieta_cuidados_prescripciones_pt_num'), table_name='dieta_cuidados_prescripciones')
    op.drop_index(op.f('ix_dieta_cuidados_prescripciones_id'), table_name='dieta_cuidados_prescripciones')
    op.drop_index(op.f('ix_dieta_cuidados_prescripciones_fecha_hora_prescripcion'), table_name='dieta_cuidados_prescripciones')
    op.drop_table('dieta_cuidados_prescripciones')
    op.drop_index(op.f('ix_auditoria_logs_id'), table_name='auditoria_logs')
    op.drop_table('auditoria_logs')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_medicos_numero_empleado'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_nombre_completo'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_id'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_huella_token'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_documentos_verificacion_qr_pt_num'), table_name='documentos_verificacion_qr')
    op.drop_index(op.f('ix_documentos_verificacion_qr_id'), table_name='documentos_verificacion_qr')
    op.drop_index(op.f('ix_documentos_verificacion_qr_fecha_generacion'), table_name='documentos_verificacion_qr')
    op.drop_index(op.f('ix_documentos_verificacion_qr_doc_uuid'), table_name='documentos_verificacion_qr')
    op.drop_index(op.f('ix_documentos_verificacion_qr_codigo_formato'), table_name='documentos_verificacion_qr')
    op.drop_index('idx_doc_qr_pt_formato_slot', table_name='documentos_verificacion_qr')
    op.drop_table('documentos_verificacion_qr')
    op.drop_index(op.f('ix_catalogo_tipos_atencion_nombre'), table_name='catalogo_tipos_atencion')
    op.drop_index(op.f('ix_catalogo_tipos_atencion_id'), table_name='catalogo_tipos_atencion')
    op.drop_table('catalogo_tipos_atencion')
    op.drop_index(op.f('ix_catalogo_formatos_id'), table_name='catalogo_formatos')
    op.drop_index(op.f('ix_catalogo_formatos_codigo'), table_name='catalogo_formatos')
    op.drop_table('catalogo_formatos')
    op.drop_index(op.f('ix_catalogo_areas_nombre'), table_name='catalogo_areas')
    op.drop_index(op.f('ix_catalogo_areas_id'), table_name='catalogo_areas')
    op.drop_table('catalogo_areas')
    op.drop_index(op.f('ix_camas_numero_cama'), table_name='camas')
    op.drop_index(op.f('ix_camas_id'), table_name='camas')
    op.drop_index(op.f('ix_camas_area'), table_name='camas')
    op.drop_table('camas')
    # ### end Alembic commands ###

